# Generated by Django 5.0.3 on 2024-06-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_list_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='text',
        ),
    ]
